# (Constants.robot_fences_021(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_024(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_026(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_027(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_029(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_031(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_032(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_033(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_034(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_035(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_036(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_037(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_038(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_039(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_040(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_041(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_042(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_043(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_044(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_045(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_046(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_047(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_048(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_049(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_050(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_051(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_052(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_053(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_054(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_055(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_056(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_057(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_058(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_059(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_060(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_061(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_062(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_063(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_064(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_065(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_066(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_067(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_068(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_069(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_070(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_071(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_072(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_073(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_074(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_075(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_076(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_077(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_078(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_079(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_080(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_081(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_082(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_083(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_084(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_085(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_086(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_087(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_088(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_089(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_090(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_091(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_092(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_093(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_094(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_095(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_096(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_097(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_098(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_099(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_100(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_101(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_102(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_103(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_104(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_105(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_106(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_107(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_108(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_109(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_110(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_111(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_112(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_113(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_114(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_115(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_116(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_117(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_118(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_119(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_120(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_121(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_122(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_123(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_124(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_125(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_126(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_127(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_128(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_129(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_130(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_131(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_132(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_133(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_134(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_135(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_136(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_137(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_138(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_139(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_140(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_141(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_142(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_143(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_144(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_145(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_146(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_147(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_148(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_149(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.robot_fences_150(), RobotFences, Solving.robot_fences_techniques()),
# (Constants.1_004(), Parks1, Solving.parks1_techniques()),
# (Constants.parks2_015(), Parks2, Solving.parks2_techniques()),
# (Constants.parks2_016(), Parks2, Solving.parks2_techniques()),
# (Constants.parks2_017(), Parks2, Solving.parks2_techniques()),
# (Constants.parks2_018(), Parks2, Solving.parks2_techniques()),
# (Constants.parks2_019(), Parks2, Solving.parks2_techniques()),
# (Constants.parks2_020(), Parks2, Solving.parks2_techniques()),
# (Constants.parks2_021(), Parks2, Solving.parks2_techniques()),
# (Constants.parks2_022(), Parks2, Solving.parks2_techniques()),
# (Constants.parks2_023(), Parks2, Solving.parks2_techniques()),
# (Constants.parks2_024(), Parks2, Solving.parks2_techniques()),
# (Constants.parks2_025(), Parks2, Solving.parks2_techniques()),
# (Constants.parks2_026(), Parks2, Solving.parks2_techniques()),
# (Constants.parks2_027(), Parks2, Solving.parks2_techniques()),
# (Constants.parks2_028(), Parks2, Solving.parks2_techniques()),
# (Constants.parks2_029(), Parks2, Solving.parks2_techniques()),
# (Constants.parks2_030(), Parks2, Solving.parks2_techniques()),
# (Constants.parks2_031(), Parks2, Solving.parks2_techniques()),
# (Constants.parks2_032(), Parks2, Solving.parks2_techniques()),
# (Constants.parks2_033(), Parks2, Solving.parks2_techniques()),
# (Constants.parks2_034(), Parks2, Solving.parks2_techniques()),
# (Constants.parks2_035(), Parks2, Solving.parks2_techniques()),
# (Constants.parks2_036(), Parks2, Solving.parks2_techniques()),
# (Constants.parks2_037(), Parks2, Solving.parks2_techniques()),
# (Constants.parks2_038(), Parks2, Solving.parks2_techniques()),
# (Constants.parks2_039(), Parks2, Solving.parks2_techniques()),
# (Constants.parks2_040(), Parks2, Solving.parks2_techniques()),
# (Constants.parks2_041(), Parks2, Solving.parks2_techniques()),


# (Constants.battle_ships_super_tanker_003(), BattleShips, Solving.battle_ships_techniques()),
# (Constants.battle_ships_001(), BattleShips, Solving.battle_ships_techniques()),
# (Constants.botanical_park_001(), Walls, Solving.walls_techniques()),
# (Constants.botanical_park_002(), Walls, Solving.walls_techniques()),
# (Constants.botanical_park_003(), Walls, Solving.walls_techniques()),
# (Constants.botanical_park_004(), Walls, Solving.walls_techniques()),
# (Constants.botanical_park_005(), Walls, Solving.walls_techniques()),
# (Constants.botanical_park_006(), Walls, Solving.walls_techniques()),
# (Constants.botanical_park_007(), Walls, Solving.walls_techniques()),
# (Constants.botanical_park_007(), Walls, Solving.walls_techniques()),
# (Constants.botanical_park_008(), Walls, Solving.walls_techniques()),
# (Constants.botanical_park_009(), Walls, Solving.walls_techniques()),
# (Constants.botanical_park_010(), Walls, Solving.walls_techniques()),
# (Constants.botanical_park_011(), Walls, Solving.walls_techniques()),
# (Constants.botanical_park_011(), Walls, Solving.walls_techniques()),
    # ('sudoku_x_wing_0', Sudoku, Solving.sudoku_techniques()),

# (Constants.sudoku_shashimi_x_wing_04(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_shashimi_x_wing_05(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_001_4x4(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_annoying_00(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_annoying_02(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_annoying_05(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_annoying_06(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_annoying_07(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_annoying_11(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_annoying_13(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_annoying_17(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_annoying_22(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_annoying_23(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_annoying_25(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_annoying_26(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_annoying_27(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_annoying_28(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_annoying_29(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_annoying_30(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_annoying_32(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_annoying_33(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_annoying_35(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_bug_0(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_hidden_pair_0(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_hidden_pair_1(), Sudoku, Solving.sudoku_techniques()),
# (Constants.magnets_033(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_034(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_035(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_036(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_037(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_038(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_039(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_040(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_041(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_042(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_043(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_044(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_045(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_046(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_047(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_048(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_049(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_050(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_051(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_052(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_053(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_054(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_055(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_056(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_057(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_058(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_059(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_060(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_063(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_082(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_083(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_119(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_022(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_023(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_024(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_025(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_026(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_027(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_028(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_029(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_030(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_031(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_032(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_015(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_016(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_017(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_018(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_019(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_020(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_021(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_008(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_009(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_010(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_011(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_013(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_012(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_002(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_004(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_005(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_006(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_007(), Magnets, Solving.magnets_techniques()),
# (Constants.magnets_003(), Magnets, Solving.magnets_techniques()),
# (Constants.kropki_001(), Kropki, Solving.kropki_techniques()),
# (Constants.kropki_002(), Kropki, Solving.kropki_techniques()),
# (Constants.kropki_003(), Kropki, Solving.kropki_techniques()),
# (Constants.kropki_004(), Kropki, Solving.kropki_techniques()),
# (Constants.kropki_005(), Kropki, Solving.kropki_techniques()),
# (Constants.kropki_006(), Kropki, Solving.kropki_techniques()),
# (Constants.kropki_007(), Kropki, Solving.kropki_techniques()),
# (Constants.kropki_008(), Kropki, Solving.kropki_techniques()),
# (Constants.kropki_009(), Kropki, Solving.kropki_techniques()),
# (Constants.kropki_010(), Kropki, Solving.kropki_techniques()),
# (Constants.kropki_011(), Kropki, Solving.kropki_techniques()),
# (Constants.kropki_012(), Kropki, Solving.kropki_techniques()),
# (Constants.kropki_013(), Kropki, Solving.kropki_techniques()),
# (Constants.kropki_014(), Kropki, Solving.kropki_techniques()),
# (Constants.kropki_015(), Kropki, Solving.kropki_techniques()),
# (Constants.kropki_016(), Kropki, Solving.kropki_techniques()),
# (Constants.kropki_017(), Kropki, Solving.kropki_techniques()),
# (Constants.kropki_018(), Kropki, Solving.kropki_techniques()),
# (Constants.kropki_019(), Kropki, Solving.kropki_techniques()),
# (Constants.kropki_020(), Kropki, Solving.kropki_techniques()),
# (Constants.kropki_021(), Kropki, Solving.kropki_techniques()),
# (Constants.kropki_022(), Kropki, Solving.kropki_techniques()),


# (Constants.sudoku_almost_locked_candidates_0(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_almost_locked_candidates_1(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_almost_locked_candidates_2(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_almost_locked_candidates_3(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_almost_locked_candidates_4(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_almost_locked_candidates_5(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_almost_locked_candidates_6(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_annoying_01(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_annoying_03(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_annoying_04(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_annoying_08(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_annoying_09(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_annoying_10(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_annoying_12(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_annoying_14(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_annoying_15(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_annoying_16(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_annoying_18(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_annoying_19(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_annoying_20(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_annoying_21(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_annoying_24(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_annoying_31(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_annoying_36(), Sudoku, Solving.sudoku_techniques()),

# (Constants.sudoku_avoidable_rectangle_type2_0(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_avoidable_rectangle_type2_1(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_avoidable_rectangle_type2_2(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_avoidable_rectangle_type2_3(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_avoidable_rectangle_type2_4(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_avoidable_rectangle_type2_5(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_avoidable_rectangle_type2_6(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_devious_0(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_devious_1(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_devious_2(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_devious_3(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_devious_4(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_devious_5(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_devious_6(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_devious_7(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_devious_8(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_diabolical_0(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_fiendish_0(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_finned_jellyfish_0(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_finned_jellyfish_1(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_finned_jellyfish_2(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_finned_jellyfish_3(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_finned_swordfish_0(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_finned_swordfish_1(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_finned_swordfish_2(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_finned_swordfish_3(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_finned_x_wing_00(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_finned_x_wing_01(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_finned_x_wing_02(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_finned_x_wing_03(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_finned_x_wing_04(), Sudoku, Solving.sudoku_techniques()),
# (Constants.futoshiki_001(), Futoshiki, Solving.futoshiki_techniques()),
# (Constants.futoshiki_002(), Futoshiki, Solving.futoshiki_techniques()),
# (Constants.futoshiki_003(), Futoshiki, Solving.futoshiki_techniques()),
# (Constants.futoshiki_015(), Futoshiki, Solving.futoshiki_techniques()),
# (Constants.futoshiki_023(), Futoshiki, Solving.futoshiki_techniques()),
# (Constants.futoshiki_010(), Futoshiki, Solving.futoshiki_techniques()),
# (Constants.futoshiki_001(), Futoshiki, Solving.futoshiki_techniques()),
# (Constants.hidden_stars_002(), HiddenStars, Solving.hidden_stars_techniques()),
# (Constants.hidden_stars_003(), HiddenStars, Solving.hidden_stars_techniques()),
# (Constants.hidden_stars_004(), HiddenStars, Solving.hidden_stars_techniques()),
# (Constants.hidden_stars_005(), HiddenStars, Solving.hidden_stars_techniques()),
# (Constants.hidden_stars_006(), HiddenStars, Solving.hidden_stars_techniques()),
# (Constants.hidden_stars_007(), HiddenStars, Solving.hidden_stars_techniques()),
# (Constants.hidden_stars_008(), HiddenStars, Solving.hidden_stars_techniques()),
# (Constants.hidden_stars_009(), HiddenStars, Solving.hidden_stars_techniques()),
# (Constants.hidden_stars_010(), HiddenStars, Solving.hidden_stars_techniques()),
# (Constants.hidden_stars_011(), HiddenStars, Solving.hidden_stars_techniques()),
# (Constants.hidden_stars_012(), HiddenStars, Solving.hidden_stars_techniques()),
# (Constants.hidden_stars_013(), HiddenStars, Solving.hidden_stars_techniques()),
# (Constants.hidden_stars_014(), HiddenStars, Solving.hidden_stars_techniques()),
# (Constants.kakuro_001(), Kakuro, Solving.kakuro_techniques()),
# (Constants.knightoku_002(), Knightoku, Solving.knightoku_techniques()),
# (Constants.knightoku_003(), Knightoku, Solving.knightoku_techniques()),
# (Constants.knightoku_004(), Knightoku, Solving.knightoku_techniques()),
# (Constants.knightoku_005(), Knightoku, Solving.knightoku_techniques()),
# (Constants.knightoku_006(), Knightoku, Solving.knightoku_techniques()),
# (Constants.knightoku_008(), Knightoku, Solving.knightoku_techniques()),
# (Constants.knightoku_009(), Knightoku, Solving.knightoku_techniques()),
# (Constants.knightoku_010(), Knightoku, Solving.knightoku_techniques()),
# (Constants.knightoku_011(), Knightoku, Solving.knightoku_techniques()),
# (Constants.knightoku_013(), Knightoku, Solving.knightoku_techniques()),
# (Constants.knightoku_014(), Knightoku, Solving.knightoku_techniques()),
# (Constants.knightoku_015(), Knightoku, Solving.knightoku_techniques()),
# (Constants.knightoku_016(), Knightoku, Solving.knightoku_techniques()),
# (Constants.knightoku_017(), Knightoku, Solving.knightoku_techniques()),
# (Constants.knightoku_014(), Knightoku, Solving.knightoku_techniques()),
# (Constants.knightoku_019(), Knightoku, Solving.knightoku_techniques()),
# (Constants.knightoku_020(), Knightoku, Solving.knightoku_techniques()),
# (Constants.knightoku_021(), Knightoku, Solving.knightoku_techniques()),
# (Constants.knightoku_022(), Knightoku, Solving.knightoku_techniques()),
# (Constants.knightoku_023(), Knightoku, Solving.knightoku_techniques()),
# (Constants.knightoku_025(), Knightoku, Solving.knightoku_techniques()),
# (Constants.knightoku_026(), Knightoku, Solving.knightoku_techniques()),
# (Constants.knightoku_027(), Knightoku, Solving.knightoku_techniques()),
# (Constants.knightoku_028(), Knightoku, Solving.knightoku_techniques()),
# (Constants.knightoku_029(), Knightoku, Solving.knightoku_techniques()),
# (Constants.knightoku_030(), Knightoku, Solving.knightoku_techniques()),
# (Constants.knightoku_031(), Knightoku, Solving.knightoku_techniques()),
# (Constants.knightoku_032(), Knightoku, Solving.knightoku_techniques()),
# (Constants.knightoku_034(), Knightoku, Solving.knightoku_techniques()),
# (Constants.knightoku_035(), Knightoku, Solving.knightoku_techniques()),
# (Constants.knightoku_037(), Knightoku, Solving.knightoku_techniques()),
# (Constants.knightoku_038(), Knightoku, Solving.knightoku_techniques()),
# (Constants.knightoku_041(), Knightoku, Solving.knightoku_techniques()),
# (Constants.knightoku_042(), Knightoku, Solving.knightoku_techniques()),
# (Constants.knightoku_043(), Knightoku, Solving.knightoku_techniques()),
# (Constants.knightoku_044(), Knightoku, Solving.knightoku_techniques()),
# (Constants.knightoku_045(), Knightoku, Solving.knightoku_techniques()),


# (Constants.tents_001(), Tents, Solving.tents_techniques()),
# (Constants.hidden_stars_001(), HiddenStars, Solving.hidden_stars_techniques()),
# (Constants.knightoku_001(), Knightoku, Solving.knightoku_techniques()),
# (Constants.clouds_001(), Clouds, Solving.clouds_techniques()),
# (Constants.magnets_001(), Magnets, Solving.magnets_techniques()),
# (Constants.lighthouses_002(), Lighthouses, Solving.lighthouses_techniques()),
# (Constants.lighthouses_003(), Lighthouses, Solving.lighthouses_techniques()),
# (Constants.lighthouses_004(), Lighthouses, Solving.lighthouses_techniques()),
# (Constants.lighthouses_005(), Lighthouses, Solving.lighthouses_techniques()),
# (Constants.lighthouses_006(), Lighthouses, Solving.lighthouses_techniques()),
# (Constants.lighthouses_007(), Lighthouses, Solving.lighthouses_techniques()),
# (Constants.lighthouses_008(), Lighthouses, Solving.lighthouses_techniques()),
# (Constants.lighthouses_009(), Lighthouses, Solving.lighthouses_techniques()),
# (Constants.lighthouses_010(), Lighthouses, Solving.lighthouses_techniques()),
# (Constants.lighthouses_011(), Lighthouses, Solving.lighthouses_techniques()),
# (Constants.lighthouses_012(), Lighthouses, Solving.lighthouses_techniques()),
# (Constants.lighthouses_013(), Lighthouses, Solving.lighthouses_techniques()),
# (Constants.lighthouses_014(), Lighthouses, Solving.lighthouses_techniques()),
# (Constants.lighthouses_015(), Lighthouses, Solving.lighthouses_techniques()),
# (Constants.lighthouses_016(), Lighthouses, Solving.lighthouses_techniques()),
# (Constants.lighthouses_017(), Lighthouses, Solving.lighthouses_techniques()),
# (Constants.lighthouses_018(), Lighthouses, Solving.lighthouses_techniques()),
# (Constants.lighthouses_019(), Lighthouses, Solving.lighthouses_techniques()),
# (Constants.lighthouses_020(), Lighthouses, Solving.lighthouses_techniques()),
# (Constants.lighthouses_021(), Lighthouses, Solving.lighthouses_techniques()),
# (Constants.lighthouses_022(), Lighthouses, Solving.lighthouses_techniques()),
# (Constants.lighthouses_023(), Lighthouses, Solving.lighthouses_techniques()),
# (Constants.lighthouses_024(), Lighthouses, Solving.lighthouses_techniques()),
# (Constants.lighthouses_025(), Lighthouses, Solving.lighthouses_techniques()),
# (Constants.lighthouses_026(), Lighthouses, Solving.lighthouses_techniques()),
# (Constants.lighthouses_027(), Lighthouses, Solving.lighthouses_techniques()),
# (Constants.lighthouses_028(), Lighthouses, Solving.lighthouses_techniques()),
# (Constants.lighthouses_029(), Lighthouses, Solving.lighthouses_techniques()),
# (Constants.lighthouses_030(), Lighthouses, Solving.lighthouses_techniques()),
# (Constants.lighthouses_031(), Lighthouses, Solving.lighthouses_techniques()),
# (Constants.lighthouses_032(), Lighthouses, Solving.lighthouses_techniques()),
# (Constants.lighthouses_033(), Lighthouses, Solving.lighthouses_techniques()),

# (Constants.mine_ships_001(), MineShips, Solving.mine_ships_techniques()),
# (Constants.mine_ships_002(), MineShips, Solving.mine_ships_techniques()),
# (Constants.mine_ships_003(), MineShips, Solving.mine_ships_techniques()),
# (Constants.minesweeper_001(), Minesweeper, Solving.minesweeper_techniques()),
# (Constants.minesweeper_002(), Minesweeper, Solving.minesweeper_techniques()),
# (Constants.minesweeper_003(), Minesweeper, Solving.minesweeper_techniques()),
# (Constants.minesweeper_006(), Minesweeper, Solving.minesweeper_techniques()),
# (Constants.minesweeper_008(), Minesweeper, Solving.minesweeper_techniques()),
# (Constants.minesweeper_009(), Minesweeper, Solving.minesweeper_techniques()),
# (Constants.minesweeper_010(), Minesweeper, Solving.minesweeper_techniques()),
# (Constants.minesweeper_011(), Minesweeper, Solving.minesweeper_techniques()),
# (Constants.minesweeper_012(), Minesweeper, Solving.minesweeper_techniques()),
# (Constants.minesweeper_013(), Minesweeper, Solving.minesweeper_techniques()),
# (Constants.minesweeper_024(), Minesweeper, Solving.minesweeper_techniques()),
# (Constants.minesweeper_006(), Minesweeper, Solving.minesweeper_techniques()),
# (Constants.minesweeper_008(), Minesweeper, Solving.minesweeper_techniques()),
# (Constants.minesweeper_009(), Minesweeper, Solving.minesweeper_techniques()),
# (Constants.minesweeper_010(), Minesweeper, Solving.minesweeper_techniques()),
# (Constants.minesweeper_011(), Minesweeper, Solving.minesweeper_techniques()),
# (Constants.minesweeper_012(), Minesweeper, Solving.minesweeper_techniques()),
# (Constants.minesweeper_013(), Minesweeper, Solving.minesweeper_techniques()),
# (Constants.minesweeper_024(), Minesweeper, Solving.minesweeper_techniques()),
# (Constants.minesweeper_004(), Minesweeper, Solving.minesweeper_techniques()),
# (Constants.minesweeper_005(), Minesweeper, Solving.minesweeper_techniques()),
# (Constants.minesweeper_014(), Minesweeper, Solving.minesweeper_techniques()),
# (Constants.minesweeper_015(), Minesweeper, Solving.minesweeper_techniques()),
# (Constants.minesweeper_017(), Minesweeper, Solving.minesweeper_techniques()),
# (Constants.minesweeper_007(), Minesweeper, Solving.minesweeper_techniques()),
# (Constants.minesweeper_016(), Minesweeper, Solving.minesweeper_techniques()),
# (Constants.nurikabe_002(), Nurikabe, Solving.nurikabe_techniques()),
# (Constants.nurikabe_003(), Nurikabe, Solving.nurikabe_techniques()),
# (Constants.nurikabe_004(), Nurikabe, Solving.nurikabe_techniques()),
# (Constants.nurikabe_005(), Nurikabe, Solving.nurikabe_techniques()),
# (Constants.nurikabe_005(), Nurikabe, Solving.nurikabe_techniques()),
# (Constants.nurikabe_006(), Nurikabe, Solving.nurikabe_techniques()),
# (Constants.nurikabe_001(), Nurikabe, Solving.nurikabe_techniques()),
# (Constants.nurikabe_007(), Nurikabe, Solving.nurikabe_techniques()),
# (Constants.nurikabe_008(), Nurikabe, Solving.nurikabe_techniques()),

# ('lightenup_006', LightenUp, Solving.lightenup_techniques()),
# ('lightenup_007', LightenUp, Solving.lightenup_techniques()),
# ('lightenup_009', LightenUp, Solving.lightenup_techniques()),
# ('lightenup_010', LightenUp, Solving.lightenup_techniques()),
# (Constants.lightenup_011(), LightenUp, Solving.lightenup_techniques()),
# (Constants.lightenup_012(), LightenUp, Solving.lightenup_techniques()),
# (Constants.lightenup_013(), LightenUp, Solving.lightenup_techniques()),
# (Constants.lightenup_014(), LightenUp, Solving.lightenup_techniques()),
# (Constants.lightenup_015(), LightenUp, Solving.lightenup_techniques()),
# (Constants.lightenup_016(), LightenUp, Solving.lightenup_techniques()),
# (Constants.lightenup_017(), LightenUp, Solving.lightenup_techniques()),
# (Constants.lightenup_018(), LightenUp, Solving.lightenup_techniques()),
# (Constants.lightenup_019(), LightenUp, Solving.lightenup_techniques()),
# (Constants.lightenup_020(), LightenUp, Solving.lightenup_techniques()),
# (Constants.lightenup_021(), LightenUp, Solving.lightenup_techniques()),
# (Constants.lightenup_022(), LightenUp, Solving.lightenup_techniques()),
# (Constants.lightenup_023(), LightenUp, Solving.lightenup_techniques()),
# (Constants.lightenup_024(), LightenUp, Solving.lightenup_techniques()),
# (Constants.lightenup_025(), LightenUp, Solving.lightenup_techniques()),
# ('lightenup_026', LightenUp, Solving.lightenup_techniques()),
# ('lightenup_027', LightenUp, Solving.lightenup_techniques()),
# ('lightenup_028', LightenUp, Solving.lightenup_techniques()),
# ('lightenup_029', LightenUp, Solving.lightenup_techniques()),
# ('lightenup_030', LightenUp, Solving.lightenup_techniques()),
# ('lightenup_031', LightenUp, Solving.lightenup_techniques()),
# (Constants.lightenup_032(), LightenUp, Solving.lightenup_techniques()),
# ('lightenup_033', LightenUp, Solving.lightenup_techniques()),
# (Constants.lightenup_034(), LightenUp, Solving.lightenup_techniques()),
# (Constants.lightenup_035(), LightenUp, Solving.lightenup_techniques()),
# (Constants.lightenup_070(), LightenUp, Solving.lightenup_techniques()),
# (Constants.lightenup_078(), LightenUp, Solving.lightenup_techniques()),
# (Constants.lightenup_080(), LightenUp, Solving.lightenup_techniques()),
#     ('lightenup_081', LightenUp, Solving.lightenup_techniques()),


# (Constants.robot_crosswords_005(), RobotCrosswords, Solving.robot_crosswords_techniques()),
# (Constants.robot_crosswords_006(), RobotCrosswords, Solving.robot_crosswords_techniques()),
# (Constants.robot_crosswords_007(), RobotCrosswords, Solving.robot_crosswords_techniques()),
# (Constants.robot_crosswords_008(), RobotCrosswords, Solving.robot_crosswords_techniques()),
# (Constants.robot_crosswords_009(), RobotCrosswords, Solving.robot_crosswords_techniques()),
# (Constants.robot_crosswords_010(), RobotCrosswords, Solving.robot_crosswords_techniques()),
# (Constants.robot_crosswords_011(), RobotCrosswords, Solving.robot_crosswords_techniques()),
# (Constants.robot_crosswords_012(), RobotCrosswords, Solving.robot_crosswords_techniques()),
# (Constants.robot_crosswords_013(), RobotCrosswords, Solving.robot_crosswords_techniques()),
# (Constants.robot_crosswords_014(), RobotCrosswords, Solving.robot_crosswords_techniques()),
# (Constants.robot_crosswords_015(), RobotCrosswords, Solving.robot_crosswords_techniques()),
# (Constants.robot_crosswords_031(), RobotCrosswords, Solving.robot_crosswords_techniques()),
# (Constants.robot_crosswords_034(), RobotCrosswords, Solving.robot_crosswords_techniques()),
# (Constants.robot_crosswords_035(), RobotCrosswords, Solving.robot_crosswords_techniques()),
# (Constants.robot_crosswords_036(), RobotCrosswords, Solving.robot_crosswords_techniques()),
# (Constants.robot_crosswords_071(), RobotCrosswords, Solving.robot_crosswords_techniques()),
# (Constants.robot_crosswords_101(), RobotCrosswords, Solving.robot_crosswords_techniques()),
# (Constants.robot_crosswords_141(), RobotCrosswords, Solving.robot_crosswords_techniques()),
# (Constants.robot_crosswords_171(), RobotCrosswords, Solving.robot_crosswords_techniques()),
# (Constants.robot_crosswords_003(), RobotCrosswords, Solving.robot_crosswords_techniques()),
# (Constants.robot_crosswords_004(), RobotCrosswords, Solving.robot_crosswords_techniques()),
# (Constants.robot_crosswords_186(), RobotCrosswords, Solving.robot_crosswords_techniques()),
# (Constants.robot_crosswords_002(), RobotCrosswords, Solving.robot_crosswords_techniques()),
# (Constants.sentinels_001(), Sentinels, Solving.sentinels_techniques()),
# (Constants.sentinels_002(), Sentinels, Solving.sentinels_techniques()),
# (Constants.sentinels_004(), Sentinels, Solving.sentinels_techniques()),
# (Constants.sentinels_006(), Sentinels, Solving.sentinels_techniques()),
# (Constants.sentinels_003(), Sentinels, Solving.sentinels_techniques()),
# (Constants.sentinels_007(), Sentinels, Solving.sentinels_techniques()),
# (Constants.power_grid_007(), PowerGrid, Solving.power_grid_techniques()),
# (Constants.power_grid_008(), PowerGrid, Solving.power_grid_techniques()),
# (Constants.power_grid_009(), PowerGrid, Solving.power_grid_techniques()),
# (Constants.power_grid_010(), PowerGrid, Solving.power_grid_techniques()),
# (Constants.power_grid_015(), PowerGrid, Solving.power_grid_techniques()),
# (Constants.power_grid_016(), PowerGrid, Solving.power_grid_techniques()),
# (Constants.power_grid_017(), PowerGrid, Solving.power_grid_techniques()),
# (Constants.abstractpainting_007(), AbstractPainting, Solving.abstractpainting_techniques()),
# (Constants.abstractpainting_008(), AbstractPainting, Solving.abstractpainting_techniques()),
# (Constants.snail3_004(), Snail3, Solving.snail3_techniques()),
# (Constants.snail3_005(), Snail3, Solving.snail3_techniques()),
# (Constants.snail3_006(), Snail3, Solving.snail3_techniques()),
# (Constants.snail3_007(), Snail3, Solving.snail3_techniques()),
# (Constants.snail3_008(), Snail3, Solving.snail3_techniques()),
# (Constants.snail3_009(), Snail3, Solving.snail3_techniques()),
# (Constants.snail3_010(), Snail3, Solving.snail3_techniques()),
# (Constants.snail3_001(), Snail3, Solving.snail3_techniques()),
# (Constants.snail3_002(), Snail3, Solving.snail3_techniques()),
# (Constants.snail3_003(), Snail3, Solving.snail3_techniques()),
# (Constants.snail3_011(), Snail3, Solving.snail3_techniques()),
# (Constants.snail3_012(), Snail3, Solving.snail3_techniques()),
# (Constants.snail3_013(), Snail3, Solving.snail3_techniques()),
# (Constants.snail3_014(), Snail3, Solving.snail3_techniques()),
# (Constants.snail3_015(), Snail3, Solving.snail3_techniques()),
# (Constants.snail3_016(), Snail3, Solving.snail3_techniques()),
# (Constants.snail3_017(), Snail3, Solving.snail3_techniques()),
# (Constants.snail3_031(), Snail3, Solving.snail3_techniques()),
# (Constants.snail3_032(), Snail3, Solving.snail3_techniques()),
# (Constants.snail3_033(), Snail3, Solving.snail3_techniques()),
# (Constants.snail3_034(), Snail3, Solving.snail3_techniques()),
# (Constants.snail3_035(), Snail3, Solving.snail3_techniques()),
# (Constants.snail3_036(), Snail3, Solving.snail3_techniques()),
# (Constants.snail3_077(), Snail3, Solving.snail3_techniques()),
# (Constants.sumscrapers_006(), Sumscrapers, Solving.sumscrapers_techniques()),
# (Constants.sumscrapers_007(), Sumscrapers, Solving.sumscrapers_techniques()),
# (Constants.sumscrapers_009(), Sumscrapers, Solving.sumscrapers_techniques()),
# (Constants.sumscrapers_010(), Sumscrapers, Solving.sumscrapers_techniques()),
# (Constants.sumscrapers_011(), Sumscrapers, Solving.sumscrapers_techniques()),
# (Constants.sumscrapers_012(), Sumscrapers, Solving.sumscrapers_techniques()),
# (Constants.sumscrapers_017(), Sumscrapers, Solving.sumscrapers_techniques()),
# (Constants.sumscrapers_018(), Sumscrapers, Solving.sumscrapers_techniques()),
# (Constants.sumscrapers_019(), Sumscrapers, Solving.sumscrapers_techniques()),
# (Constants.sumscrapers_020(), Sumscrapers, Solving.sumscrapers_techniques()),
# (Constants.tents_009(), Tents, Solving.tents_techniques()),
# (Constants.walls_001(), Walls, Solving.walls_techniques()),
# (Constants.walls_002(), Walls, Solving.walls_techniques()),
# (Constants.walls_003(), Walls, Solving.walls_techniques()),
# (Constants.walls_004(), Walls, Solving.walls_techniques()),
# (Constants.walls_005(), Walls, Solving.walls_techniques()),
# (Constants.walls_006(), Walls, Solving.walls_techniques()),
# (Constants.walls_007(), Walls, Solving.walls_techniques()),
# (Constants.walls_008(), Walls, Solving.walls_techniques()),
# (Constants.walls_009(), Walls, Solving.walls_techniques()),
# (Constants.walls_010(), Walls, Solving.walls_techniques()),
# (Constants.walls_011(), Walls, Solving.walls_techniques()),
# (Constants.walls_012(), Walls, Solving.walls_techniques()),
# (Constants.walls_013(), Walls, Solving.walls_techniques()),
# (Constants.walls_014(), Walls, Solving.walls_techniques()),
# (Constants.walls_015(), Walls, Solving.walls_techniques()),
# (Constants.walls_016(), Walls, Solving.walls_techniques()),
# (Constants.walls_017(), Walls, Solving.walls_techniques()),
# (Constants.walls_018(), Walls, Solving.walls_techniques()),
# (Constants.walls_019(), Walls, Solving.walls_techniques()),
# (Constants.walls_020(), Walls, Solving.walls_techniques()),
# (Constants.walls_021(), Walls, Solving.walls_techniques()),
# (Constants.walls_022(), Walls, Solving.walls_techniques()),
# (Constants.walls_023(), Walls, Solving.walls_techniques()),
# (Constants.walls_024(), Walls, Solving.walls_techniques()),
# (Constants.walls_025(), Walls, Solving.walls_techniques()),
# (Constants.walls_026(), Walls, Solving.walls_techniques()),
# (Constants.walls_027(), Walls, Solving.walls_techniques()),
# (Constants.walls_028(), Walls, Solving.walls_techniques()),
# (Constants.walls_029(), Walls, Solving.walls_techniques()),
# (Constants.walls_030(), Walls, Solving.walls_techniques()),
# (Constants.walls_031(), Walls, Solving.walls_techniques()),
# (Constants.walls_032(), Walls, Solving.walls_techniques()),
# (Constants.walls_033(), Walls, Solving.walls_techniques()),
# (Constants.walls_034(), Walls, Solving.walls_techniques()),
# (Constants.walls_035(), Walls, Solving.walls_techniques()),
# (Constants.walls_036(), Walls, Solving.walls_techniques()),
# (Constants.walls_037(), Walls, Solving.walls_techniques()),
# (Constants.walls_038(), Walls, Solving.walls_techniques()),
# (Constants.walls_039(), Walls, Solving.walls_techniques()),
# (Constants.walls_040(), Walls, Solving.walls_techniques()),
# (Constants.walls_041(), Walls, Solving.walls_techniques()),
# (Constants.walls_042(), Walls, Solving.walls_techniques()),
# (Constants.walls_043(), Walls, Solving.walls_techniques()),
# (Constants.walls_044(), Walls, Solving.walls_techniques()),
# (Constants.walls_045(), Walls, Solving.walls_techniques()),
# (Constants.walls_048(), Walls, Solving.walls_techniques()),
# (Constants.walls_049(), Walls, Solving.walls_techniques()),
# (Constants.walls_050(), Walls, Solving.walls_techniques()),
# (Constants.walls_051(), Walls, Solving.walls_techniques()),
# (Constants.walls_062(), Walls, Solving.walls_techniques()),
# (Constants.walls_063(), Walls, Solving.walls_techniques()),
# (Constants.walls_064(), Walls, Solving.walls_techniques()),
# (Constants.walls_065(), Walls, Solving.walls_techniques()),
# (Constants.walls_066(), Walls, Solving.walls_techniques()),
# (Constants.walls_067(), Walls, Solving.walls_techniques()),
# (Constants.walls_068(), Walls, Solving.walls_techniques()),
# (Constants.walls_069(), Walls, Solving.walls_techniques()),
# (Constants.walls_070(), Walls, Solving.walls_techniques()),
# (Constants.walls_071(), Walls, Solving.walls_techniques()),
# (Constants.walls_072(), Walls, Solving.walls_techniques()),
# (Constants.walls_092(), Walls, Solving.walls_techniques()),
# (Constants.walls_101(), Walls, Solving.walls_techniques()),
# (Constants.walls_109(), Walls, Solving.walls_techniques()),
# (Constants.walls_111(), Walls, Solving.walls_techniques()),
# (Constants.sudoku_shashimi_swordfish_5(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_shashimi_x_wing_00(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_shashimi_x_wing_01(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_shashimi_x_wing_02(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_shashimi_x_wing_03(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_shashimi_x_wing_06(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_shashimi_x_wing_07(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_shashimi_x_wing_08(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_shashimi_x_wing_09(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_simple_coloring_trap_0(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_sue_de_coq_0(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_sue_de_coq_1(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_sue_de_coq_2(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_swordfish_0(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_swordfish_1(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_swordfish_2(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_swordfish_3(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_swordfish_4(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_swordfish_5(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_swordfish_6(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_unique_rectangle_type3_00(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_unique_rectangle_type3_01(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_unique_rectangle_type3_02(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_unique_rectangle_type3_03(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_unique_rectangle_type3_04(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_unique_rectangle_type3_05(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_unique_rectangle_type3_06(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_unique_rectangle_type3_07(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_wxyz_wing_0(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_wxyz_wing_1(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_wxyz_wing_19(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_wxyz_wing_2(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_wxyz_wing_3(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_wxyz_wing_4(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_wxyz_wing_5(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_wxyz_wing_6(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_wxyz_wing_7(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_wxyz_wing_8(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_wxyz_wing_9(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_w_wing_type_d_0(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_w_wing_type_d_1(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_w_wing_type_d_2(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_w_wing_type_d_3(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_w_wing_type_d_4(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_w_wing_type_d_5(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_w_wing_type_d_6(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_xyz_wing_0(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_xyz_wing_1(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_xyz_wing_2(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_xyz_wing_3(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_xyz_wing_4(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_xyz_wing_5(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_xyz_wing_6(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_xyz_wing_7(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_xyz_wing_8(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_xyz_wing_9(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_xy_chain_0(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_xy_chain_1(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_xy_chain_2(), Sudoku, Solving.sudoku_techniques()),

# (Constants.sudoku_x_chain_0(), Sudoku, Solving.sudoku_techniques()),

# (Constants.sudoku_finned_x_wing_05(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_finned_x_wing_06(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_finned_x_wing_07(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_finned_x_wing_08(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_finned_x_wing_09(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_finned_x_wing_10(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_finned_x_wing_11(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_finned_x_wing_12(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_finned_x_wing_13(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_finned_x_wing_14(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_finned_x_wing_15(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_finned_x_wing_16(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_finned_x_wing_17(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_fishy_cycle_0(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_fishy_cycle_1(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_hidden_quad_0(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_hidden_quad_1(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_hidden_quad_2(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_hidden_quad_3(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_hidden_quad_4(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_hidden_quad_5(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_hidden_quad_6(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_hidden_quad_7(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_hidden_quad_8(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_hidden_quad_9(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_hidden_triple_0(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_hidden_triple_2(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_hidden_triple_3(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_hidden_triple_4(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_hidden_triple_5(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_hidden_triple_6(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_hidden_unique_rectangle_0(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_hidden_unique_rectangle_1(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_hidden_unique_rectangle_2(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_hidden_unique_rectangle_3(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_hidden_unique_rectangle_4(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_hidden_unique_rectangle_5(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_jellyfish_0(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_jellyfish_1(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_jellyfish_2(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_maelstrom_0(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_medusa_coloring_3d_0(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_naked_quad_0(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_naked_quad_1(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_naked_quad_2(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_naked_quad_3(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_naked_quad_4(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_naked_quad_5(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_naked_quad_6(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_naked_quad_7(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_nightmare_0(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_remote_pair_0(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_remote_pair_1(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_remote_pair_2(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_shashimi_jellyfish_0(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_shashimi_jellyfish_1(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_shashimi_jellyfish_2(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_shashimi_jellyfish_3(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_shashimi_swordfish_0(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_shashimi_swordfish_1(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_shashimi_swordfish_2(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_shashimi_swordfish_3(), Sudoku, Solving.sudoku_techniques()),
# (Constants.sudoku_shashimi_swordfish_4(), Sudoku, Solving.sudoku_techniques()),


# (Sudoku,
#  FinnedXWing(),
#  Constants.sudoku_explicit_finned_x_wing_2_fin_rows_actual(),
#  Constants.sudoku_explicit_finned_x_wing_2_fin_rows_expected()),
# (Sudoku,
#  FinnedXWing(),
#  Constants.sudoku_explicit_finned_x_wing_1_fin_rows_actual(),
#  Constants.sudoku_explicit_finned_x_wing_1_fin_rows_expected()),


# (Magnets,
#  MagnetsZero(),
#  Constants.magnets_zero_cols_actual(),
#  Constants.magnets_zero_cols_expected()),
# (Magnets,
#  MagnetsPair(),
#  Constants.magnets_pairs_actual(),
#  Constants.magnets_pairs_expected()),
# (Magnets,
#  MagnetsFullHouse(),
#  Constants.magnets_full_house_even_actual(),
#  Constants.magnets_full_house_even_expected()),
# (Magnets,
#  MagnetsZero(),
#  Constants.magnets_zero_rows_actual(),
#  Constants.magnets_zero_rows_expected()),


# (Kropki,
#      KropkiWw(),
#      Constants.kropki_explicit_ww_actual(),
#      Constants.kropki_explicit_ww_expected()),
# (Parks1,
#  Parks1HiddenSingle(),
#  Constants.parks1_explicit_hidden_single_actual(),
#  Constants.parks1_explicit_hidden_single_expected()),
# (Parks1,
#  Parks1CrossHatch(),
#  Constants.parks1_explicit_cross_hatch_actual(),
#  Constants.parks1_explicit_cross_hatch_expected()),

#     (Kropki,
#      Techs.KropkiHiddenSingle(),
#      Constants.kropki_explicit_hidden_single_actual(),
#      Constants.kropki_explicit_hidden_single_expected()),
#     (Kropki,
#      Techs.KropkiHiddenPair(),
#      Constants.kropki_explicit_hidden_pair_actual(),
#      Constants.kropki_explicit_hidden_pair_expected()),
#     (Kropki,
#      Techs.KropkiHiddenTriple(),
#      Constants.kropki_explicit_hidden_triple_actual(),
#      Constants.kropki_explicit_hidden_triple_expected()),
#     (Kropki,
#      Techs.KropkiHiddenQuad(),
#      Constants.kropki_explicit_hidden_quad_actual(),
#      Constants.kropki_explicit_hidden_quad_expected()),
#     (Kropki,
#      Techs.KropkiNakedPair(),
#      Constants.kropki_explicit_naked_pair_actual(),
#      Constants.kropki_explicit_naked_pair_expected()),
#     (Kropki,
#      Techs.KropkiNakedTriple(),
#      Constants.kropki_explicit_naked_triple_actual(),
#      Constants.kropki_explicit_naked_triple_expected()),
#     (Kropki,
#      Techs.KropkiNakedQuad(),
#      Constants.kropki_explicit_naked_quad_actual(),
#      Constants.kropki_explicit_naked_quad_expected()),
#     (Kropki,
#      Techs.KropkiLockedCandidatesPointing(),
#      Constants.kropki_explicit_locked_candidates_pointing_actual(),
#      Constants.kropki_explicit_locked_candidates_pointing_expected()),
#     (Kropki,
#      Techs.KropkiLockedCandidatesClaiming(),
#      Constants.kropki_explicit_locked_candidates_claiming_actual(),
#      Constants.kropki_explicit_locked_candidates_claiming_expected()),
#     (Futoshiki,
#      Techs.FutoshikiCrossHatch(),
#      Constants.futoshiki_explicit_cross_hatch_actual(),
#      Constants.futoshiki_explicit_cross_hatch_expected()),
#     (Futoshiki,
#      Techs.FutoshikiHiddenSingle(),
#      Constants.futoshiki_explicit_hidden_single_actual(),
#      Constants.futoshiki_explicit_hidden_single_expected()),

#     (Minesweeper,
#      Techs.MinesweeperSolver(),
#      Constants.minesweeper_explicit_0_actual(),
#      Constants.minesweeper_explicit_0_expected()),
#     (Sudoku,
#      Techs.XyChain(),
#      Constants.sudoku_explicit_xy_chain_actual(),
#      Constants.sudoku_explicit_xy_chain_expected()),
#     (Sudoku,
#      Techs.FishyCycle(),
#      Constants.sudoku_explicit_fishy_cycle_actual(),
#      Constants.sudoku_explicit_fishy_cycle_expected()),
#     (Sudoku,
#      Techs.SimpleColoring(),
#      Constants.sudoku_explicit_simple_coloring_actual(),
#      Constants.sudoku_explicit_simple_coloring_expected()),
#     (Sudoku,
#      Techs.SueDeCoq(),
#      Constants.sudoku_explicit_sue_de_coq_rows_actual(),
#      Constants.sudoku_explicit_sue_de_coq_rows_expected()),
#     (Sudoku,
#      Techs.SueDeCoq(),
#      Constants.sudoku_explicit_sue_de_coq_cols_actual(),
#      Constants.sudoku_explicit_sue_de_coq_cols_expected()),
#     (Sudoku,
#      Techs.UniqueRectangleType3(),
#      Constants.sudoku_explicit_unique_rectangle_type3_col_chute_fences_2_fins_actual(),
#      Constants.sudoku_explicit_unique_rectangle_type3_col_chute_fences_2_fins_expected()),
#     (Sudoku,
#      Techs.UniqueRectangleType3(),
#      Constants.sudoku_explicit_unique_rectangle_type3_row_chute_west_cols_2_fins_actual(),
#      Constants.sudoku_explicit_unique_rectangle_type3_row_chute_west_cols_2_fins_expected()),
#     (Sudoku,
#      Techs.ShashimiJellyFish(),
#      Constants.sudoku_explicit_shashimi_jelly_fish_cols_actual(),
#      Constants.sudoku_explicit_shashimi_jelly_fish_cols_expected()),
#     (Sudoku,
#      Techs.FinnedXWing(), Constants.sudoku_explicit_finned_x_wing_1_fin_cols_actual(),
#      Constants.sudoku_explicit_finned_x_wing_1_fin_cols_expected()),
#     (Sudoku,
#      Techs.FinnedSwordFish(), Constants.sudoku_explicit_finned_sword_fish_cols_actual(),
#      Constants.sudoku_explicit_finned_sword_fish_cols_expected()),
#     (Sudoku,
#      Techs.FinnedJellyFish(),
#      Constants.sudoku_explicit_finned_jelly_fish_cols_actual(),
#      Constants.sudoku_explicit_finned_jelly_fish_cols_expected()),
#     (Sudoku,
#      Techs.ShashimiSwordFish(),
#      Constants.sudoku_explicit_shashimi_sword_fish_1_fin_rows_actual(),
#      Constants.sudoku_explicit_shashimi_sword_fish_1_fin_rows_expected()),
#     (Sudoku,
#      Techs.ShashimiSwordFish(),
#      Constants.sudoku_explicit_shashimi_sword_fish_2_fin_cols_actual(),
#      Constants.sudoku_explicit_shashimi_sword_fish_2_fin_cols_expected()),
#     (Sudoku,
#      Techs.XChain(),
#      Constants.sudoku_explicit_x_chain_actual(),
#      Constants.sudoku_explicit_x_chain_expected()),
#     (Sudoku,
#      Techs.ShashimiSwordFish(),
#      Constants.sudoku_explicit_shashimi_sword_fish_1_fin_cols_actual(),
#      Constants.sudoku_explicit_shashimi_sword_fish_1_fin_cols_expected()),
#     (Sudoku,
#      Techs.HiddenTriple(),
#      Constants.sudoku_explicit_hidden_triple_rows_actual(),
#      Constants.sudoku_explicit_hidden_triple_rows_expected()),
#     (Sudoku,
#      Techs.HiddenTriple(),
#      Constants.sudoku_explicit_hidden_triple_fences_actual(),
#      Constants.sudoku_explicit_hidden_triple_fences_expected()),
#     (Sudoku,
#      Techs.HiddenQuad(),
#      Constants.sudoku_explicit_hidden_quad_rows_actual(),
#      Constants.sudoku_explicit_hidden_quad_rows_expected()),
#     (Sudoku,
#      Techs.HiddenQuad(),
#      Constants.sudoku_explicit_hidden_quad_cols_actual(),
#      Constants.sudoku_explicit_hidden_quad_cols_expected()),
#     (Sudoku,
#      Techs.AvoidableRectangleType2(),
#      Constants.sudoku_explicit_avoidable_rectangle_type2_east_actual(),
#      Constants.sudoku_explicit_avoidable_rectangle_type2_east_expected()),
#     (Sudoku,
#      Techs.WxyzWing(),
#      Constants.sudoku_explicit_wxyz_wing_3_fences_row_chute_actual(),
#      Constants.sudoku_explicit_wxyz_wing_3_fences_row_chute_expected()),
#     (Sudoku,
#      Techs.WxyzWing(),
#      Constants.sudoku_explicit_wxyz_wing_2_fences_row_chute_actual(),
#      Constants.sudoku_explicit_wxyz_wing_2_fences_row_chute_expected()),
#     (Sudoku,
#      Techs.WxyzWing(),
#      Constants.sudoku_explicit_wxyz_wing_3_fences_col_chute_actual(),
#      Constants.sudoku_explicit_wxyz_wing_3_fences_col_chute_expected()),
#     (Sudoku,
#      Techs.WxyzWing(),
#      Constants.sudoku_explicit_wxyz_wing_2_fences_col_chute_actual(),
#      Constants.sudoku_explicit_wxyz_wing_2_fences_col_chute_expected()),
#     (Skyscrapers,
#      Techs.SkyscrapersCrossHatch(),
#      Constants.skyscrapers_explicit_cross_hatch_actual(),
#      Constants.skyscrapers_explicit_cross_hatch_expected()),
#     (Skyscrapers,
#      Techs.SkyscrapersHiddenSingle(),
#      Constants.skyscrapers_explicit_hidden_single_actual(),
#      Constants.skyscrapers_explicit_hidden_single_expected()),
#     (Skyscrapers,
#      Techs.SkyscrapersEdges(),
#      Constants.skyscrapers_explicit_edges_actual(),
#      Constants.skyscrapers_explicit_edges_expected()),
#     (Sudoku,
#      Techs.AvoidableRectangleType2(),
#      Constants.sudoku_explicit_avoidable_rectangle_type2_north_actual(),
#      Constants.sudoku_explicit_avoidable_rectangle_type2_north_expected()),
#     (Sudoku,
#      Techs.FinnedSwordFish(),
#      Constants.sudoku_explicit_finned_sword_fish_rows_actual(),
#      Constants.sudoku_explicit_finned_sword_fish_rows_expected()),
#     (Sudoku,
#      Techs.FinnedJellyFish(),
#      Constants.sudoku_explicit_finned_jelly_fish_rows_actual(),
#      Constants.sudoku_explicit_finned_jelly_fish_rows_expected()),

#     (Sudoku,
#      Techs.ShashimiSwordFish(),
#      Constants.sudoku_explicit_shashimi_sword_fish_2_fin_rows_actual(),
#      Constants.sudoku_explicit_shashimi_sword_fish_2_fin_rows_expected()),
#     (Sudoku,
#      Techs.ShashimiJellyFish(),
#      Constants.sudoku_explicit_shashimi_jelly_fish_rows_actual(),
#      Constants.sudoku_explicit_shashimi_jelly_fish_rows_expected()),
#     (Sudoku,
#      Techs.AlmostLockedCandidatesClaiming(),
#      Constants.sudoku_explicit_almost_locked_candidates_claming_rows_actual(),
#      Constants.sudoku_explicit_almost_locked_candidates_claming_rows_expected()),
#     (Sudoku,
#      Techs.AlmostLockedCandidatesPointing(),
#      Constants.sudoku_explicit_almost_locked_candidates_pointing_rows_actual(),
#      Constants.sudoku_explicit_almost_locked_candidates_pointing_rows_expected()),


#     (Sudoku,
#      Techs.AvoidableRectangleType2(),
#      Constants.sudoku_explicit_avoidable_rectangle_type2_south_actual(),
#      Constants.sudoku_explicit_avoidable_rectangle_type2_south_expected()),
#     (Sudoku,
#      Techs.HiddenTriple(),
#      Constants.sudoku_explicit_hidden_triple_cols_actual(),
#      Constants.sudoku_explicit_hidden_triple_cols_expected()),
#     (Sudoku,
#      Techs.HiddenQuad(),
#      Constants.sudoku_explicit_hidden_quad_fences_actual(),
#      Constants.sudoku_explicit_hidden_quad_fences_expected()),



#     (Sudoku,
#      Techs.NakedQuad(),
#      Constants.sudoku_explicit_naked_quad_rows_actual(),
#      Constants.sudoku_explicit_naked_quad_rows_expected()),
#     (Sudoku,
#      Techs.NakedQuad(),
#      Constants.sudoku_explicit_naked_quad_cols_actual(),
#      Constants.sudoku_explicit_naked_quad_cols_expected()),
#     (Sudoku,
#      Techs.NakedQuad(),
#      Constants.sudoku_explicit_naked_quad_fences_actual(),
#      Constants.sudoku_explicit_naked_quad_fences_expected()),
# (Sudoku,
#  XyWing(),
#  Constants.sudoku_explicit_xy_wing_2_fences_row_chute_actual(),
#  Constants.sudoku_explicit_xy_wing_2_fences_row_chute_expected()),
# (Sudoku,
#  XyWing(),
#  Constants.sudoku_explicit_xy_wing_2_fences_col_chute_actual(),
#  Constants.sudoku_explicit_xy_wing_2_fences_col_chute_expected()),

# (Constants.skyscrapers_004(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_006(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_007(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_008(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_009(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_010(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_011(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_012(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_013(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_014(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_015(), Skyscrapers, Solving.skyscrapers_techniques()),
# # (Constants.skyscrapers_016(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_017(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_018(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_019(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_020(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_021(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_022(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_023(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_024(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_025(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_026(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_027(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_028(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_029(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_030(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_skydoku_001(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_skydoku_004(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_skydoku_021(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_skydoku_030(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_skydoku_036(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tcbig_001(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tcbig_002(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tcbig_003(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tcbig_004(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tcbig_013(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tcbig_019(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tcbig_030(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tcbig_033(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tcbig_039(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tcbig_046(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tcbig_062(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tcbig_068(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tcbig_087(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tcbig_093(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tcbig_100(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tcbig_119(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_003(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_004(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_005(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_006(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_007(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_008(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_009(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_010(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_011(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_012(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_013(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_014(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_016(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_017(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_018(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_019(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_025(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_026(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_027(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_028(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_029(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_030(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_031(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_032(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_033(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_034(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_038(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_039(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_046(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_051(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_052(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_056(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_057(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_062(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_068(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_087(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_093(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_100(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_119(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_130(), Skyscrapers, Solving.skyscrapers_techniques()),
# (Constants.skyscrapers_tc_135(), Skyscrapers, Solving.skyscrapers_techniques()),


# (Sudoku,
#  ShashimiXWing(),
#  Constants.sudoku_explicit_shashimi_x_wing_1_fin_cols_actual(),
#  Constants.sudoku_explicit_shashimi_x_wing_1_fin_cols_expected()),
# (Sudoku,
#  ShashimiXWing(),
#  Constants.sudoku_explicit_shashimi_x_wing_1_fin_rows_actual(),
#  Constants.sudoku_explicit_shashimi_x_wing_1_fin_rows_expected()),
# (Sudoku,
#  ShashimiXWing(),
#  Constants.sudoku_explicit_shashimi_x_wing_2_fin_rows_actual(),
#  Constants.sudoku_explicit_shashimi_x_wing_2_fin_rows_expected()),
#
# (Sudoku,
#  ShashimiXWing(),
#  Constants.sudoku_explicit_shashimi_x_wing_2_fin_cols_actual(),
#  Constants.sudoku_explicit_shashimi_x_wing_2_fin_cols_expected()),
# (Sudoku,
#  FinnedXWing(),
#  Constants.sudoku_explicit_finned_x_wing_1_fin_cols_actual(),
#  Constants.sudoku_explicit_finned_x_wing_1_fin_cols_expected()),
# (Sudoku,
#  FinnedXWing(),
#  Constants.sudoku_explicit_finned_x_wing_2_fin_cols_actual(),
#  Constants.sudoku_explicit_finned_x_wing_2_fin_cols_expected()),
# (Sudoku,
#  FinnedXWing(),
#  Constants.sudoku_explicit_finned_x_wing_2_fin_cols_actual(),
#  Constants.sudoku_explicit_finned_x_wing_2_fin_cols_expected()),

# ("tenner_007", Tenner, Solving.tenner_techniques()),
# (Constants.tenner_010(), Tenner, Solving.tenner_techniques()),
# (Constants.tenner_011(), Tenner, Solving.tenner_techniques()),
# (Constants.tenner_012(), Tenner, Solving.tenner_techniques()),
# (Constants.tenner_013(), Tenner, Solving.tenner_techniques()),
# ("tenner_014", Tenner, Solving.tenner_techniques()),
# (Constants.tenner_015(), Tenner, Solving.tenner_techniques()),
# (Constants.tenner_016(), Tenner, Solving.tenner_techniques()),
# ('tenner_017', Tenner, Solving.tenner_techniques()),
# (Constants.tenner_018(), Tenner, Solving.tenner_techniques()),
# ('tenner_020', Tenner, Solving.tenner_techniques()),
# (Constants.tenner_021(), Tenner, Solving.tenner_techniques()),
# (Constants.tenner_022(), Tenner, Solving.tenner_techniques()),
# (Constants.tenner_023(), Tenner, Solving.tenner_techniques()),
# (Constants.tenner_024(), Tenner, Solving.tenner_techniques()),
# (Constants.tenner_challenging_001(), Tenner, Solving.tenner_techniques()),
# (Constants.tenner_challenging_002(), Tenner, Solving.tenner_techniques()),
# (Constants.tenner_challenging_003(), Tenner, Solving.tenner_techniques()),
# (Constants.tenner_challenging_004(), Tenner, Solving.tenner_techniques()),
# ('tenner_harder_001', Tenner, Solving.tenner_techniques()),
# ('tenner_harder_002', Tenner, Solving.tenner_techniques()),
# (Constants.tenner_harder_003(), Tenner, Solving.tenner_techniques()),
# (Constants.tenner_harder_004(), Tenner, Solving.tenner_techniques()),

# ('abstractpainting_008', AbstractPainting, Solving.abstractpainting_techniques()),
# ('abstractpainting_010', AbstractPainting, Solving.abstractpainting_techniques()),
# ('abstractpainting_012', AbstractPainting, Solving.abstractpainting_techniques()),
# ('abstractpainting_013', AbstractPainting, Solving.abstractpainting_techniques()),
# ('abstractpainting_014', AbstractPainting, Solving.abstractpainting_techniques()),

# ('abstractpainting_031', AbstractPainting, Solving.abstractpainting_techniques()),
# ('abstractpainting_035', AbstractPainting, Solving.abstractpainting_techniques()),
# ('abstractpainting_051', AbstractPainting, Solving.abstractpainting_techniques()),
# ('abstractpainting_101', AbstractPainting, Solving.abstractpainting_techniques()),
# ('abstractpainting_151', AbstractPainting, Solving.abstractpainting_techniques()),
# ('abstractpainting_191', AbstractPainting, Solving.abstractpainting_techniques()),


# ("parks1_009", Parks1, Solving.parks1_techniques()),
# ("parks1_010", Parks1, Solving.parks1_techniques()),
# ("parks1_spring_016", Parks1, Solving.parks1_techniques()),
# ("parks1_spring_027", Parks1, Solving.parks1_techniques()),
# ("parks1_spring_046", Parks1, Solving.parks1_techniques()),
# ("parks1_spring_051", Parks1, Solving.parks1_techniques()),
# ("parks1_winter_037", Parks1, Solving.parks1_techniques()),
# ("parks1_winter_038", Parks1, Solving.parks1_techniques()),
# ("parks1_winter_039", Parks1, Solving.parks1_techniques()),
# ("parks1_winter_040", Parks1, Solving.parks1_techniques()),
# ("parks1_winter_041", Parks1, Solving.parks1_techniques()),
# ("parks1_winter_042", Parks1, Solving.parks1_techniques()),
# ("parks1_winter_044", Parks1, Solving.parks1_techniques()),
# ("parks1_winter_045", Parks1, Solving.parks1_techniques()),
# ("parks1_winter_046", Parks1, Solving.parks1_techniques()),
# ("parks1_winter_047", Parks1, Solving.parks1_techniques()),
# ("parks1_winter_048", Parks1, Solving.parks1_techniques()),
# ("parks1_winter_050", Parks1, Solving.parks1_techniques()),
# ("parks1_winter_051", Parks1, Solving.parks1_techniques()),
# ('sudoku_avoidable_rectangle_type1_00", Sudoku, Solving.sudoku_techniques()),
# ('sudoku_naked_triple_7", Sudoku, Solving.sudoku_techniques()),
# ('sudoku_remote_pair_row", Sudoku, Solving.sudoku_techniques()),
# ('sudoku_xy_wing_00", Sudoku, Solving.sudoku_techniques()),
# ("sudoku_avoidable_rectangle_type1_01", Sudoku, Solving.sudoku_techniques()),
# ("sudoku_avoidable_rectangle_type1_02", Sudoku, Solving.sudoku_techniques()),
# ("sudoku_avoidable_rectangle_type1_03", Sudoku, Solving.sudoku_techniques()),
# ("sudoku_avoidable_rectangle_type1_04", Sudoku, Solving.sudoku_techniques()),
# ("sudoku_avoidable_rectangle_type1_05", Sudoku, Solving.sudoku_techniques()),
# ("sudoku_avoidable_rectangle_type1_07", Sudoku, Solving.sudoku_techniques()),
# ("sudoku_avoidable_rectangle_type1_08", Sudoku, Solving.sudoku_techniques()),
# ("sudoku_avoidable_rectangle_type1_09", Sudoku, Solving.sudoku_techniques()),
# ("sudoku_avoidable_rectangle_type1_10", Sudoku, Solving.sudoku_techniques()),
# ("sudoku_avoidable_rectangle_type1_11", Sudoku, Solving.sudoku_techniques()),
# ("sudoku_avoidable_rectangle_type1_12", Sudoku, Solving.sudoku_techniques()),
# ("sudoku_avoidable_rectangle_type1_13", Sudoku, Solving.sudoku_techniques()),
# ("sudoku_xy_wing_01", Sudoku, Solving.sudoku_techniques()),
# ("sudoku_xy_wing_02", Sudoku, Solving.sudoku_techniques()),
# ("sudoku_xy_wing_03", Sudoku, Solving.sudoku_techniques()),
# ("sudoku_xy_wing_04", Sudoku, Solving.sudoku_techniques()),
# ("sudoku_xy_wing_05", Sudoku, Solving.sudoku_techniques()),
# ("sudoku_xy_wing_06", Sudoku, Solving.sudoku_techniques()),
# ("sudoku_xy_wing_07", Sudoku, Solving.sudoku_techniques()),
# ("sudoku_xy_wing_08", Sudoku, Solving.sudoku_techniques()),
# ("sudoku_xy_wing_09", Sudoku, Solving.sudoku_techniques()),
# ("sudoku_xy_wing_10", Sudoku, Solving.sudoku_techniques()),
# ("sudoku_xy_wing_11", Sudoku, Solving.sudoku_techniques()),
# ("sudoku_hidden_pair_row", Sudoku, Solving.sudoku_techniques()),
# ("sudoku_hidden_pair_col", Sudoku, Solving.sudoku_techniques()),
# ("sudoku_hidden_pair_fence", Sudoku, Solving.sudoku_techniques()),
# ("sudoku_hidden_triple_row", Sudoku, Solving.sudoku_techniques()),
# ("sudoku_hidden_triple_col", Sudoku, Solving.sudoku_techniques()),
# ("sudoku_hidden_triple_fence", Sudoku, Solving.sudoku_techniques()),
# ("sudoku_hidden_quad_row", Sudoku, Solving.sudoku_techniques()),
# ("sudoku_hidden_quad_col", Sudoku, Solving.sudoku_techniques()),
# ("sudoku_hidden_quad_fence", Sudoku, Solving.sudoku_techniques()),
# ("sudoku_swordfish_of_5_in_rows", Sudoku, Solving.sudoku_techniques()),
# ("sudoku_swordfish_of_8_in_cols", Sudoku, Solving.sudoku_techniques()),
# ("sudoku_jellyfish_of_1_in_rows", Sudoku, Solving.sudoku_techniques()),
# ("sudoku_jellyfish_of_3_in_cols", Sudoku, Solving.sudoku_techniques()),
# ["sudoku_difficult_01", Sudoku, Solving.sudoku_techniques()],
# ["sudoku_difficult_02", Sudoku, Solving.sudoku_techniques()],
# ["sudoku_difficult_04", Sudoku, Solving.sudoku_techniques()],
# ["sudoku_difficult_05", Sudoku, Solving.sudoku_techniques()],
# ["sudoku_difficult_07", Sudoku, Solving.sudoku_techniques()],
# ["sudoku_difficult_08", Sudoku, Solving.sudoku_techniques()],
# ["sudoku_difficult_09", Sudoku, Solving.sudoku_techniques()],
# ["sudoku_difficult_15", Sudoku, Solving.sudoku_techniques()],
# ["sudoku_difficult_17", Sudoku, Solving.sudoku_techniques()],
# ["sudoku_difficult_20", Sudoku, Solving.sudoku_techniques()],
# ["sudoku_difficult_21", Sudoku, Solving.sudoku_techniques()],
# ["sudoku_difficult_28", Sudoku, Solving.sudoku_techniques()],
# ["sudoku_difficult_31", Sudoku, Solving.sudoku_techniques()],
# ["sudoku_difficult_35", Sudoku, Solving.sudoku_techniques()],
# ("sudoku_unique_rectangle_type4_south_cols", Sudoku, Solving.sudoku_techniques()),
# ['sudoku_difficult_11', Sudoku, Solving.sudoku_techniques()]
# ("sudoku_unique_rectangle_type2_07", Sudoku, Solving.sudoku_techniques()),
# ('sudoku_x_wing_1', Sudoku, Solving.sudoku_techniques()),
# ('lighthouses_003', Lighthouses, Solving.lighthouses_techniques()),
# ('lighthouses_004', Lighthouses, Solving.lighthouses_techniques()),
# ('lighthouses_005', Lighthouses, Solving.lighthouses_techniques()),
# # ('lighthouses_006', Lighthouses, Solving.lighthouses_techniques()),
# ('sudoku_x_wing_2', Sudoku, Solving.sudoku_techniques()),
    # ('sudoku_x_wing_3', Sudoku, Solving.sudoku_techniques()),
# ('sudoku_naked_triple_8', Sudoku, Solving.sudoku_techniques()),
# (Sudoku,
#  FinnedXWing(),
#  Constants.sudoku_explicit_finned_x_wing_1_fin_rows_actual(),
#  Constants.sudoku_explicit_finned_x_wing_1_fin_rows_expected()),
# ('mathrax_001', Mathrax, Solving.mathrax_techniques()),

# (Sudoku,
#      FinnedXWing(),
#      Constants.sudoku_explicit_finned_x_wing_2_fin_rows_actual(),
#      Constants.sudoku_explicit_finned_x_wing_2_fin_rows_expected()),


# ['sudoku_difficult_14', Sudoku, [
#     CrossHatch(),
#     HiddenSingle(),
#     NakedPair(),
#     LockedCandidatesPointing(),
#     LockedCandidatesClaiming(),
#     UniqueRectangleType1(),
#     UniqueRectangleType2(),
#     UniqueRectangleType4(),
#     FinnedXWing(),
#     Bug(),
#     HiddenPair(),
#     NakedTriple(),
#     XWing(),
#     XyWing(),
# ]],
# ['sudoku_difficult_16', Sudoku, [
#     CrossHatch(),
#     HiddenSingle(),
#     NakedPair(),
#     LockedCandidatesPointing(),
#     LockedCandidatesClaiming(),
#     UniqueRectangleType1(),
#     UniqueRectangleType2(),
#     UniqueRectangleType4(),
#     FinnedXWing(),
#     Bug(),
#     HiddenPair(),
#     NakedTriple(),
#     XWing(),
#     XyWing(),
# ]],